export const Categories = [
    'None',
    'Cryptocurrency',
    'Cybersecurity',
    'Fixit',
    'Food',
    'Gaming',
    'Haiku',
    'Help',
    'History',
    'Housing',
    'Jokes',
    'Legal',
    'Money',
    'Movies',
    'Music',
    'Pets',
    'Photo',
    'Science',
    'Software',
    'Source Code',
    'Spirit',
    'Sports',
    'Travel',
    'Tv',
    'Writing'
]